---
DAConfig:
  fqdn: galaxy.digitastuces.com
  main_iface: eth0
  services:
    - monservicebidon
  #  - salt-master

usersandgroups:
  users:
    {% for user, values in stack['digitastuces']['team_infra'].items() %}
    {{ user }}:
      {{ values }}
    {% endfor %}
    {% for user, values in stack['digitastuces']['team_dev'].items() %}
    {{ user }}:
      {{ values }}
    {% endfor %}
    root:
      password: $6$ZIsj50f1YxiiC1Sj$dUcAHky.le32Cat.iu88.D/u5c3tlZUfMn/ZV02BBiw364536WArFTgaw7WrOk/XozATDX9RpmxyjSyMWDybJ1


DAInfos:
  Customer: digitastuces
  Hoster: Online
  Type: System
  DataCenter: prodinf1
  DeploymentDate: 2022/10/23
