---
DAConfig:
  fqdn: galaxy.digitastuces.com
  main_iface: eth0
  services:
    - salt-master


DAInfos:
  Customer: digitastuces
  Hoster: Online
  Type: System
  DataCenter: prodinf1
  DeploymentDate: 2022/10/23
